### ISSUE TITLE
Emails prompting to finish setup actions redirect to bad URLs

### ISSUE THREAD

**Issue by jaspax** [textmagic/textmagic-rest-perl#1]
After completing a sign-up to allow me to get an API key, I received two emails which prompted me to finish setup. Unfortunately, both of these emails redirected me to bad urls.

The first email contained a button saying [Please choose your sender settings](http://email.textmagic.com/c/eJxdT7tuwjAU_RoyIj-JPWRoBQ2iigQIUJXFMvaN6xKT4ASI-PoGpqrSGc5wnt39qnoIba17UDeInW_OyttspOrkeLl75LLJP4fBBcjflgVsEpshAdQkEQz4tn-q68apIyJECIErYo4ghaCWMWlSiUHKSmCR-IwgzJEkGBMusZxinCI0ZVygdMJQD0MftPNmapqQfGfCIEKZZIgfLQHgFcWEcEtYOkNcVzypswkhI5Lu74dxzcjVrfzafdzjkHeaLzYPur8stkWTxOxHd60exj4XtK9fXTb6VhkdWu3dWXU9tM8UazpFDYU4j_nqcFgVxfYUfHzfi3-Gl1bN5bbcXay7rJdGzK7u5h9xzX4By-tzeQ), and clicking that link resulted in redirecting to `http://%22%22`, rather than any textmagic.com address.

The second email contained a button saying [Finish TextMagic setup wizard](http://email.textmagic.com/c/eJxdT7tuwjAU_Ro8ovgdDxnSSAwgJGhVNWWxHPsSHPIwSQjp3zcwVZXOcIbzHB53PUITajOCnqAffNdq75KF6v4b1OlrMzE2b982D5UVVfWeIZdEMVCLerDgw_hU112pC3Um0knKKRdFbM6UcyGo5SoixBhgyCckwjxSBGPCFafrmAgRrRVmXKxYNMI8Nqb0dm27Bl0SamRhJDCCwVouLOWFwmCc4gRLKR2qkxUhC9Dw98OyZuE6D7v0J2V8Ol6a-BRXJQRvWtQnlRmCmZe-sjG-fnW53gdtTROML1s9jBCeKc4O-nob9gfykecFT_fTlbZwuuXdP8NLq60Xn_P9fFDd8ba9Z9U2hXDd_QIQnHSF), and clicking on that link also redirected to `http://%22%22`.

This was confirmed on Windows 10 using both Chrome and Edge, and on Ubuntu 14.04.3 using Firefox.

**Comment by dmitry-textmagic** [comment]
Hello, thank you for your report. These emails were just introduced, and we will fix it soon. However, as I can see, it wasn't interrupted your sign-up process, and you have completed it successfully.

**Comment by dmitry-textmagic** [comment]
These email were fixed. Closing.
